/*
 * Copyright 2014 JHC Systems Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sqlest.ast

trait TableFunctions {
  abstract class TableFunction1[A1](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1](column1: Column[B1])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1]) =
      TableFunction(tableName, aliasedAs, Seq(column1))
  }

  abstract class TableFunction2[A1, A2](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2](column1: Column[B1], column2: Column[B2])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2))
  }

  abstract class TableFunction3[A1, A2, A3](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3](column1: Column[B1], column2: Column[B2], column3: Column[B3])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3))
  }

  abstract class TableFunction4[A1, A2, A3, A4](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4))
  }

  abstract class TableFunction5[A1, A2, A3, A4, A5](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5))
  }

  abstract class TableFunction6[A1, A2, A3, A4, A5, A6](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6))
  }

  abstract class TableFunction7[A1, A2, A3, A4, A5, A6, A7](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7))
  }

  abstract class TableFunction8[A1, A2, A3, A4, A5, A6, A7, A8](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8))
  }

  abstract class TableFunction9[A1, A2, A3, A4, A5, A6, A7, A8, A9](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9))
  }

  abstract class TableFunction10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10))
  }

  abstract class TableFunction11[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11))
  }

  abstract class TableFunction12[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12))
  }

  abstract class TableFunction13[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13))
  }

  abstract class TableFunction14[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14))
  }

  abstract class TableFunction15[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15))
  }

  abstract class TableFunction16[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16))
  }

  abstract class TableFunction17[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17))
  }

  abstract class TableFunction18[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17], column18: Column[B18])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17], column18Equivalence: ColumnTypeEquivalence[A18, B18]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17, column18))
  }

  abstract class TableFunction19[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17], column18: Column[B18], column19: Column[B19])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17], column18Equivalence: ColumnTypeEquivalence[A18, B18], column19Equivalence: ColumnTypeEquivalence[A19, B19]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17, column18, column19))
  }

  abstract class TableFunction20[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17], column18: Column[B18], column19: Column[B19], column20: Column[B20])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17], column18Equivalence: ColumnTypeEquivalence[A18, B18], column19Equivalence: ColumnTypeEquivalence[A19, B19], column20Equivalence: ColumnTypeEquivalence[A20, B20]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17, column18, column19, column20))
  }

  abstract class TableFunction21[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20, B21](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17], column18: Column[B18], column19: Column[B19], column20: Column[B20], column21: Column[B21])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17], column18Equivalence: ColumnTypeEquivalence[A18, B18], column19Equivalence: ColumnTypeEquivalence[A19, B19], column20Equivalence: ColumnTypeEquivalence[A20, B20], column21Equivalence: ColumnTypeEquivalence[A21, B21]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17, column18, column19, column20, column21))
  }

  abstract class TableFunction22[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22](val tableName: String, val aliasedAs: Option[String] = None) extends BaseTable {
    def apply[B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15, B16, B17, B18, B19, B20, B21, B22](column1: Column[B1], column2: Column[B2], column3: Column[B3], column4: Column[B4], column5: Column[B5], column6: Column[B6], column7: Column[B7], column8: Column[B8], column9: Column[B9], column10: Column[B10], column11: Column[B11], column12: Column[B12], column13: Column[B13], column14: Column[B14], column15: Column[B15], column16: Column[B16], column17: Column[B17], column18: Column[B18], column19: Column[B19], column20: Column[B20], column21: Column[B21], column22: Column[B22])(implicit column1Equivalence: ColumnTypeEquivalence[A1, B1], column2Equivalence: ColumnTypeEquivalence[A2, B2], column3Equivalence: ColumnTypeEquivalence[A3, B3], column4Equivalence: ColumnTypeEquivalence[A4, B4], column5Equivalence: ColumnTypeEquivalence[A5, B5], column6Equivalence: ColumnTypeEquivalence[A6, B6], column7Equivalence: ColumnTypeEquivalence[A7, B7], column8Equivalence: ColumnTypeEquivalence[A8, B8], column9Equivalence: ColumnTypeEquivalence[A9, B9], column10Equivalence: ColumnTypeEquivalence[A10, B10], column11Equivalence: ColumnTypeEquivalence[A11, B11], column12Equivalence: ColumnTypeEquivalence[A12, B12], column13Equivalence: ColumnTypeEquivalence[A13, B13], column14Equivalence: ColumnTypeEquivalence[A14, B14], column15Equivalence: ColumnTypeEquivalence[A15, B15], column16Equivalence: ColumnTypeEquivalence[A16, B16], column17Equivalence: ColumnTypeEquivalence[A17, B17], column18Equivalence: ColumnTypeEquivalence[A18, B18], column19Equivalence: ColumnTypeEquivalence[A19, B19], column20Equivalence: ColumnTypeEquivalence[A20, B20], column21Equivalence: ColumnTypeEquivalence[A21, B21], column22Equivalence: ColumnTypeEquivalence[A22, B22]) =
      TableFunction(tableName, aliasedAs, Seq(column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17, column18, column19, column20, column21, column22))
  }
}
